export const SIDEBAR_DRAWER_OPEN = "SIDEBAR_DRAWER_OPEN";
export const SIDEBAR_DRAWER_CLOSED = "SIDEBAR_DRAWER_CLOSED";
export const ACTIVE_USERNAME = "ACTIVE_USERNAME";
export const FRIEND_SELECTED = "FRIEND_SELECTED";