export const SIDEBAR_DRAWER_OPEN = "SIDEBAR_DRAWER_OPEN";
export const SIDEBAR_DRAWER_CLOSED = "SIDEBAR_DRAWER_CLOSED";
export const ACTIVE_USERNAME = "ACTIVE_USERNAME";
export const FRIEND_SELECTED = "FRIEND_SELECTED";
export const NOTIFICATIONS = "NOTIFICATIONS";
export const NEW_REQUEST_NOTIFICATION = "NEW_REQUEST_NOTIFICATION";
export const ACCEPTED_REQUEST_NOTIFICATION = "ACCEPTED_REQUEST_NOTIFICATION";
export const PENDING_REQUEST_NOTIFICATION = "PENDING_REQUEST_NOTIFICATION";